// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protoc/namenode.proto

package com.rothsCode.litehdfs.common.protoc;

public interface OperateLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OperateLog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string operateType = 1;</code>
   *
   * @return The operateType.
   */
  String getOperateType();

  /**
   * <code>string operateType = 1;</code>
   *
   * @return The bytes for operateType.
   */
  com.google.protobuf.ByteString
  getOperateTypeBytes();

  /**
   * <code>string path = 2;</code>
   *
   * @return The path.
   */
  String getPath();

  /**
   * <code>string path = 2;</code>
   *
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
  getPathBytes();

  /**
   * <code>int64 txId = 3;</code>
   *
   * @return The txId.
   */
  long getTxId();

  /**
   * <code>.ProtoFileInfo fileInfo = 4;</code>
   *
   * @return Whether the fileInfo field is set.
   */
  boolean hasFileInfo();

  /**
   * <code>.ProtoFileInfo fileInfo = 4;</code>
   *
   * @return The fileInfo.
   */
  ProtoFileInfo getFileInfo();

  /**
   * <code>.ProtoFileInfo fileInfo = 4;</code>
   */
  ProtoFileInfoOrBuilder getFileInfoOrBuilder();
}
