// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protoc/namenode.proto

package com.rothsCode.litehdfs.common.protoc;

public interface ProtoNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1;</code>
   *
   * @return The path.
   */
  String getPath();

  /**
   * <code>string path = 1;</code>
   *
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
  getPathBytes();

  /**
   * <code>bool isFileNode = 2;</code>
   *
   * @return The isFileNode.
   */
  boolean getIsFileNode();

  /**
   * <code>map&lt;string, .ProtoNode&gt; childNodes = 3;</code>
   */
  int getChildNodesCount();

  /**
   * <code>map&lt;string, .ProtoNode&gt; childNodes = 3;</code>
   */
  boolean containsChildNodes(
      String key);

  /**
   * Use {@link #getChildNodesMap()} instead.
   */
  @Deprecated
  java.util.Map<String, ProtoNode>
  getChildNodes();

  /**
   * <code>map&lt;string, .ProtoNode&gt; childNodes = 3;</code>
   */
  java.util.Map<String, ProtoNode>
  getChildNodesMap();

  /**
   * <code>map&lt;string, .ProtoNode&gt; childNodes = 3;</code>
   */
  /* nullable */
  ProtoNode getChildNodesOrDefault(
      String key,
      /* nullable */
      ProtoNode defaultValue);

  /**
   * <code>map&lt;string, .ProtoNode&gt; childNodes = 3;</code>
   */
  ProtoNode getChildNodesOrThrow(
      String key);

  /**
   * <code>.ProtoFileInfo fileInfo = 4;</code>
   *
   * @return Whether the fileInfo field is set.
   */
  boolean hasFileInfo();

  /**
   * <code>.ProtoFileInfo fileInfo = 4;</code>
   *
   * @return The fileInfo.
   */
  ProtoFileInfo getFileInfo();

  /**
   * <code>.ProtoFileInfo fileInfo = 4;</code>
   */
  ProtoFileInfoOrBuilder getFileInfoOrBuilder();
}
