// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protoc/namenode.proto

package com.rothsCode.litehdfs.common.protoc;

/**
 * Protobuf type {@code ProtoFileInfo}
 */
public final class ProtoFileInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProtoFileInfo)
    ProtoFileInfoOrBuilder {

  public static final int FILESIZE_FIELD_NUMBER = 1;
  public static final int FILETYPE_FIELD_NUMBER = 2;
  public static final int FILENAME_FIELD_NUMBER = 3;
  public static final int PARENTFILENAME_FIELD_NUMBER = 4;
  public static final int ABSOLUTEPATH_FIELD_NUMBER = 5;
  public static final int CREATETIME_FIELD_NUMBER = 6;
  public static final int UPDATETIME_FIELD_NUMBER = 7;
  public static final int CREATEUSER_FIELD_NUMBER = 8;
  public static final int UPDATEUSER_FIELD_NUMBER = 9;
  public static final int HOSTNAME_FIELD_NUMBER = 10;
  public static final int BLKDATANODES_FIELD_NUMBER = 11;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:ProtoFileInfo)
  private static final ProtoFileInfo DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<ProtoFileInfo>
      PARSER = new com.google.protobuf.AbstractParser<ProtoFileInfo>() {
    @Override
    public ProtoFileInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  static {
    DEFAULT_INSTANCE = new ProtoFileInfo();
  }

  private int fileSize_ = 0;
  @SuppressWarnings("serial")
  private volatile Object fileType_ = "";
  @SuppressWarnings("serial")
  private volatile Object fileName_ = "";
  @SuppressWarnings("serial")
  private volatile Object parentFileName_ = "";
  @SuppressWarnings("serial")
  private volatile Object absolutePath_ = "";
  private long createTime_ = 0L;
  private long updateTime_ = 0L;
  @SuppressWarnings("serial")
  private volatile Object createUser_ = "";
  @SuppressWarnings("serial")
  private volatile Object updateUser_ = "";
  @SuppressWarnings("serial")
  private volatile Object hostName_ = "";
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringList blkDataNodes_;
  private byte memoizedIsInitialized = -1;

  // Use ProtoFileInfo.newBuilder() to construct.
  private ProtoFileInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private ProtoFileInfo() {
    fileType_ = "";
    fileName_ = "";
    parentFileName_ = "";
    absolutePath_ = "";
    createUser_ = "";
    updateUser_ = "";
    hostName_ = "";
    blkDataNodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return Namenode.internal_static_ProtoFileInfo_descriptor;
  }

  public static ProtoFileInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static ProtoFileInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static ProtoFileInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static ProtoFileInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static ProtoFileInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static ProtoFileInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static ProtoFileInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static ProtoFileInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ProtoFileInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ProtoFileInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static ProtoFileInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static ProtoFileInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(ProtoFileInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static ProtoFileInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<ProtoFileInfo> parser() {
    return PARSER;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoFileInfo();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  @Override
  protected FieldAccessorTable
  internalGetFieldAccessorTable() {
    return Namenode.internal_static_ProtoFileInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ProtoFileInfo.class, Builder.class);
  }

  /**
   * <code>int32 fileSize = 1;</code>
   *
   * @return The fileSize.
   */
  @Override
  public int getFileSize() {
    return fileSize_;
  }

  /**
   * <code>string fileType = 2;</code>
   *
   * @return The fileType.
   */
  @Override
  public String getFileType() {
    Object ref = fileType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fileType_ = s;
      return s;
    }
  }

  /**
   * <code>string fileType = 2;</code>
   *
   * @return The bytes for fileType.
   */
  @Override
  public com.google.protobuf.ByteString
  getFileTypeBytes() {
    Object ref = fileType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fileType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string fileName = 3;</code>
   *
   * @return The fileName.
   */
  @Override
  public String getFileName() {
    Object ref = fileName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }

  /**
   * <code>string fileName = 3;</code>
   *
   * @return The bytes for fileName.
   */
  @Override
  public com.google.protobuf.ByteString
  getFileNameBytes() {
    Object ref = fileName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string parentFileName = 4;</code>
   *
   * @return The parentFileName.
   */
  @Override
  public String getParentFileName() {
    Object ref = parentFileName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      parentFileName_ = s;
      return s;
    }
  }

  /**
   * <code>string parentFileName = 4;</code>
   *
   * @return The bytes for parentFileName.
   */
  @Override
  public com.google.protobuf.ByteString
  getParentFileNameBytes() {
    Object ref = parentFileName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      parentFileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string absolutePath = 5;</code>
   *
   * @return The absolutePath.
   */
  @Override
  public String getAbsolutePath() {
    Object ref = absolutePath_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      absolutePath_ = s;
      return s;
    }
  }

  /**
   * <code>string absolutePath = 5;</code>
   *
   * @return The bytes for absolutePath.
   */
  @Override
  public com.google.protobuf.ByteString
  getAbsolutePathBytes() {
    Object ref = absolutePath_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      absolutePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>int64 createTime = 6;</code>
   *
   * @return The createTime.
   */
  @Override
  public long getCreateTime() {
    return createTime_;
  }

  /**
   * <code>int64 updateTime = 7;</code>
   *
   * @return The updateTime.
   */
  @Override
  public long getUpdateTime() {
    return updateTime_;
  }

  /**
   * <code>string createUser = 8;</code>
   *
   * @return The createUser.
   */
  @Override
  public String getCreateUser() {
    Object ref = createUser_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      createUser_ = s;
      return s;
    }
  }

  /**
   * <code>string createUser = 8;</code>
   *
   * @return The bytes for createUser.
   */
  @Override
  public com.google.protobuf.ByteString
  getCreateUserBytes() {
    Object ref = createUser_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      createUser_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string updateUser = 9;</code>
   *
   * @return The updateUser.
   */
  @Override
  public String getUpdateUser() {
    Object ref = updateUser_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      updateUser_ = s;
      return s;
    }
  }

  /**
   * <code>string updateUser = 9;</code>
   *
   * @return The bytes for updateUser.
   */
  @Override
  public com.google.protobuf.ByteString
  getUpdateUserBytes() {
    Object ref = updateUser_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      updateUser_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>string hostName = 10;</code>
   *
   * @return The hostName.
   */
  @Override
  public String getHostName() {
    Object ref = hostName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      hostName_ = s;
      return s;
    }
  }

  /**
   * <code>string hostName = 10;</code>
   *
   * @return The bytes for hostName.
   */
  @Override
  public com.google.protobuf.ByteString
  getHostNameBytes() {
    Object ref = hostName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      hostName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>repeated string blkDataNodes = 11;</code>
   *
   * @return A list containing the blkDataNodes.
   */
  public com.google.protobuf.ProtocolStringList
  getBlkDataNodesList() {
    return blkDataNodes_;
  }

  /**
   * <code>repeated string blkDataNodes = 11;</code>
   *
   * @return The count of blkDataNodes.
   */
  public int getBlkDataNodesCount() {
    return blkDataNodes_.size();
  }

  /**
   * <code>repeated string blkDataNodes = 11;</code>
   *
   * @param index The index of the element to return.
   * @return The blkDataNodes at the given index.
   */
  public String getBlkDataNodes(int index) {
    return blkDataNodes_.get(index);
  }

  /**
   * <code>repeated string blkDataNodes = 11;</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the blkDataNodes at the given index.
   */
  public com.google.protobuf.ByteString
  getBlkDataNodesBytes(int index) {
    return blkDataNodes_.getByteString(index);
  }

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) {
      return true;
    }
    if (isInitialized == 0) {
      return false;
    }

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (fileSize_ != 0) {
      output.writeInt32(1, fileSize_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fileName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentFileName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, parentFileName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(absolutePath_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, absolutePath_);
    }
    if (createTime_ != 0L) {
      output.writeInt64(6, createTime_);
    }
    if (updateTime_ != 0L) {
      output.writeInt64(7, updateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createUser_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, createUser_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(updateUser_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, updateUser_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, hostName_);
    }
    for (int i = 0; i < blkDataNodes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, blkDataNodes_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) {
      return size;
    }

    size = 0;
    if (fileSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, fileSize_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fileName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentFileName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, parentFileName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(absolutePath_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, absolutePath_);
    }
    if (createTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createTime_);
    }
    if (updateTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, updateTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createUser_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, createUser_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(updateUser_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, updateUser_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, hostName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < blkDataNodes_.size(); i++) {
        dataSize += computeStringSizeNoTag(blkDataNodes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getBlkDataNodesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof ProtoFileInfo)) {
      return super.equals(obj);
    }
    ProtoFileInfo other = (ProtoFileInfo) obj;

    if (getFileSize()
        != other.getFileSize()) {
      return false;
    }
    if (!getFileType()
        .equals(other.getFileType())) {
      return false;
    }
    if (!getFileName()
        .equals(other.getFileName())) {
      return false;
    }
    if (!getParentFileName()
        .equals(other.getParentFileName())) {
      return false;
    }
    if (!getAbsolutePath()
        .equals(other.getAbsolutePath())) {
      return false;
    }
    if (getCreateTime()
        != other.getCreateTime()) {
      return false;
    }
    if (getUpdateTime()
        != other.getUpdateTime()) {
      return false;
    }
    if (!getCreateUser()
        .equals(other.getCreateUser())) {
      return false;
    }
    if (!getUpdateUser()
        .equals(other.getUpdateUser())) {
      return false;
    }
    if (!getHostName()
        .equals(other.getHostName())) {
      return false;
    }
    if (!getBlkDataNodesList()
        .equals(other.getBlkDataNodesList())) {
      return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getFileSize();
    hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getFileType().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (37 * hash) + PARENTFILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getParentFileName().hashCode();
    hash = (37 * hash) + ABSOLUTEPATH_FIELD_NUMBER;
    hash = (53 * hash) + getAbsolutePath().hashCode();
    hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTime());
    hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpdateTime());
    hash = (37 * hash) + CREATEUSER_FIELD_NUMBER;
    hash = (53 * hash) + getCreateUser().hashCode();
    hash = (37 * hash) + UPDATEUSER_FIELD_NUMBER;
    hash = (53 * hash) + getUpdateUser().hashCode();
    hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostName().hashCode();
    if (getBlkDataNodesCount() > 0) {
      hash = (37 * hash) + BLKDATANODES_FIELD_NUMBER;
      hash = (53 * hash) + getBlkDataNodesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @Override
  public com.google.protobuf.Parser<ProtoFileInfo> getParserForType() {
    return PARSER;
  }

  @Override
  public ProtoFileInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code ProtoFileInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProtoFileInfo)
      ProtoFileInfoOrBuilder {

    private int bitField0_;
    private int fileSize_;
    private Object fileType_ = "";
    private Object fileName_ = "";
    private Object parentFileName_ = "";
    private Object absolutePath_ = "";
    private long createTime_;
    private long updateTime_;
    private Object createUser_ = "";
    private Object updateUser_ = "";
    private Object hostName_ = "";
    private com.google.protobuf.LazyStringList blkDataNodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;

    // Construct using com.rothsCode.litehdfs.common.protoc.ProtoFileInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return Namenode.internal_static_ProtoFileInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return Namenode.internal_static_ProtoFileInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoFileInfo.class, Builder.class);
    }

    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fileSize_ = 0;
      fileType_ = "";
      fileName_ = "";
      parentFileName_ = "";
      absolutePath_ = "";
      createTime_ = 0L;
      updateTime_ = 0L;
      createUser_ = "";
      updateUser_ = "";
      hostName_ = "";
      blkDataNodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000400);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return Namenode.internal_static_ProtoFileInfo_descriptor;
    }

    @Override
    public ProtoFileInfo getDefaultInstanceForType() {
      return ProtoFileInfo.getDefaultInstance();
    }

    @Override
    public ProtoFileInfo build() {
      ProtoFileInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ProtoFileInfo buildPartial() {
      ProtoFileInfo result = new ProtoFileInfo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ProtoFileInfo result) {
      if (((bitField0_ & 0x00000400) != 0)) {
        blkDataNodes_ = blkDataNodes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000400);
      }
      result.blkDataNodes_ = blkDataNodes_;
    }

    private void buildPartial0(ProtoFileInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fileSize_ = fileSize_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fileType_ = fileType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.fileName_ = fileName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.parentFileName_ = parentFileName_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.absolutePath_ = absolutePath_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.createTime_ = createTime_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.updateTime_ = updateTime_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.createUser_ = createUser_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.updateUser_ = updateUser_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.hostName_ = hostName_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ProtoFileInfo) {
        return mergeFrom((ProtoFileInfo) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ProtoFileInfo other) {
      if (other == ProtoFileInfo.getDefaultInstance()) {
        return this;
      }
      if (other.getFileSize() != 0) {
        setFileSize(other.getFileSize());
      }
      if (!other.getFileType().isEmpty()) {
        fileType_ = other.fileType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getParentFileName().isEmpty()) {
        parentFileName_ = other.parentFileName_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getAbsolutePath().isEmpty()) {
        absolutePath_ = other.absolutePath_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getCreateTime() != 0L) {
        setCreateTime(other.getCreateTime());
      }
      if (other.getUpdateTime() != 0L) {
        setUpdateTime(other.getUpdateTime());
      }
      if (!other.getCreateUser().isEmpty()) {
        createUser_ = other.createUser_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getUpdateUser().isEmpty()) {
        updateUser_ = other.updateUser_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getHostName().isEmpty()) {
        hostName_ = other.hostName_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.blkDataNodes_.isEmpty()) {
        if (blkDataNodes_.isEmpty()) {
          blkDataNodes_ = other.blkDataNodes_;
          bitField0_ = (bitField0_ & ~0x00000400);
        } else {
          ensureBlkDataNodesIsMutable();
          blkDataNodes_.addAll(other.blkDataNodes_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              fileSize_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              fileType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              fileName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              parentFileName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              absolutePath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              createTime_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              updateTime_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              createUser_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              updateUser_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              hostName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              String s = input.readStringRequireUtf8();
              ensureBlkDataNodesIsMutable();
              blkDataNodes_.add(s);
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    /**
     * <code>int32 fileSize = 1;</code>
     *
     * @return The fileSize.
     */
    @Override
    public int getFileSize() {
      return fileSize_;
    }

    /**
     * <code>int32 fileSize = 1;</code>
     *
     * @param value The fileSize to set.
     * @return This builder for chaining.
     */
    public Builder setFileSize(int value) {

      fileSize_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     * <code>int32 fileSize = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearFileSize() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fileSize_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>string fileType = 2;</code>
     *
     * @return The fileType.
     */
    public String getFileType() {
      Object ref = fileType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string fileType = 2;</code>
     *
     * @param value The fileType to set.
     * @return This builder for chaining.
     */
    public Builder setFileType(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      fileType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    /**
     * <code>string fileType = 2;</code>
     *
     * @return The bytes for fileType.
     */
    public com.google.protobuf.ByteString
    getFileTypeBytes() {
      Object ref = fileType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string fileType = 2;</code>
     *
     * @param value The bytes for fileType to set.
     * @return This builder for chaining.
     */
    public Builder setFileTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      fileType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    /**
     * <code>string fileType = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearFileType() {
      fileType_ = getDefaultInstance().getFileType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    /**
     * <code>string fileName = 3;</code>
     *
     * @return The fileName.
     */
    public String getFileName() {
      Object ref = fileName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string fileName = 3;</code>
     *
     * @param value The fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileName(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      fileName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    /**
     * <code>string fileName = 3;</code>
     *
     * @return The bytes for fileName.
     */
    public com.google.protobuf.ByteString
    getFileNameBytes() {
      Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string fileName = 3;</code>
     *
     * @param value The bytes for fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      fileName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    /**
     * <code>string fileName = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearFileName() {
      fileName_ = getDefaultInstance().getFileName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    /**
     * <code>string parentFileName = 4;</code>
     *
     * @return The parentFileName.
     */
    public String getParentFileName() {
      Object ref = parentFileName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        parentFileName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string parentFileName = 4;</code>
     *
     * @param value The parentFileName to set.
     * @return This builder for chaining.
     */
    public Builder setParentFileName(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      parentFileName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    /**
     * <code>string parentFileName = 4;</code>
     *
     * @return The bytes for parentFileName.
     */
    public com.google.protobuf.ByteString
    getParentFileNameBytes() {
      Object ref = parentFileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        parentFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string parentFileName = 4;</code>
     *
     * @param value The bytes for parentFileName to set.
     * @return This builder for chaining.
     */
    public Builder setParentFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      parentFileName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    /**
     * <code>string parentFileName = 4;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearParentFileName() {
      parentFileName_ = getDefaultInstance().getParentFileName();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    /**
     * <code>string absolutePath = 5;</code>
     *
     * @return The absolutePath.
     */
    public String getAbsolutePath() {
      Object ref = absolutePath_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        absolutePath_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string absolutePath = 5;</code>
     *
     * @param value The absolutePath to set.
     * @return This builder for chaining.
     */
    public Builder setAbsolutePath(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      absolutePath_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    /**
     * <code>string absolutePath = 5;</code>
     *
     * @return The bytes for absolutePath.
     */
    public com.google.protobuf.ByteString
    getAbsolutePathBytes() {
      Object ref = absolutePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        absolutePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string absolutePath = 5;</code>
     *
     * @param value The bytes for absolutePath to set.
     * @return This builder for chaining.
     */
    public Builder setAbsolutePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      absolutePath_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    /**
     * <code>string absolutePath = 5;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearAbsolutePath() {
      absolutePath_ = getDefaultInstance().getAbsolutePath();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    /**
     * <code>int64 createTime = 6;</code>
     *
     * @return The createTime.
     */
    @Override
    public long getCreateTime() {
      return createTime_;
    }

    /**
     * <code>int64 createTime = 6;</code>
     *
     * @param value The createTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTime(long value) {

      createTime_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    /**
     * <code>int64 createTime = 6;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearCreateTime() {
      bitField0_ = (bitField0_ & ~0x00000020);
      createTime_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>int64 updateTime = 7;</code>
     *
     * @return The updateTime.
     */
    @Override
    public long getUpdateTime() {
      return updateTime_;
    }

    /**
     * <code>int64 updateTime = 7;</code>
     *
     * @param value The updateTime to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateTime(long value) {

      updateTime_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    /**
     * <code>int64 updateTime = 7;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearUpdateTime() {
      bitField0_ = (bitField0_ & ~0x00000040);
      updateTime_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>string createUser = 8;</code>
     *
     * @return The createUser.
     */
    public String getCreateUser() {
      Object ref = createUser_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createUser_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string createUser = 8;</code>
     *
     * @param value The createUser to set.
     * @return This builder for chaining.
     */
    public Builder setCreateUser(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      createUser_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    /**
     * <code>string createUser = 8;</code>
     *
     * @return The bytes for createUser.
     */
    public com.google.protobuf.ByteString
    getCreateUserBytes() {
      Object ref = createUser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        createUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string createUser = 8;</code>
     *
     * @param value The bytes for createUser to set.
     * @return This builder for chaining.
     */
    public Builder setCreateUserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      createUser_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    /**
     * <code>string createUser = 8;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearCreateUser() {
      createUser_ = getDefaultInstance().getCreateUser();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }

    /**
     * <code>string updateUser = 9;</code>
     *
     * @return The updateUser.
     */
    public String getUpdateUser() {
      Object ref = updateUser_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        updateUser_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string updateUser = 9;</code>
     *
     * @param value The updateUser to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateUser(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      updateUser_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    /**
     * <code>string updateUser = 9;</code>
     *
     * @return The bytes for updateUser.
     */
    public com.google.protobuf.ByteString
    getUpdateUserBytes() {
      Object ref = updateUser_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        updateUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string updateUser = 9;</code>
     *
     * @param value The bytes for updateUser to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateUserBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      updateUser_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    /**
     * <code>string updateUser = 9;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearUpdateUser() {
      updateUser_ = getDefaultInstance().getUpdateUser();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }

    /**
     * <code>string hostName = 10;</code>
     *
     * @return The hostName.
     */
    public String getHostName() {
      Object ref = hostName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string hostName = 10;</code>
     *
     * @param value The hostName to set.
     * @return This builder for chaining.
     */
    public Builder setHostName(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      hostName_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    /**
     * <code>string hostName = 10;</code>
     *
     * @return The bytes for hostName.
     */
    public com.google.protobuf.ByteString
    getHostNameBytes() {
      Object ref = hostName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string hostName = 10;</code>
     *
     * @param value The bytes for hostName to set.
     * @return This builder for chaining.
     */
    public Builder setHostNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      hostName_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    /**
     * <code>string hostName = 10;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearHostName() {
      hostName_ = getDefaultInstance().getHostName();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }

    private void ensureBlkDataNodesIsMutable() {
      if (!((bitField0_ & 0x00000400) != 0)) {
        blkDataNodes_ = new com.google.protobuf.LazyStringArrayList(blkDataNodes_);
        bitField0_ |= 0x00000400;
      }
    }

    /**
     * <code>repeated string blkDataNodes = 11;</code>
     *
     * @return A list containing the blkDataNodes.
     */
    public com.google.protobuf.ProtocolStringList
    getBlkDataNodesList() {
      return blkDataNodes_.getUnmodifiableView();
    }

    /**
     * <code>repeated string blkDataNodes = 11;</code>
     *
     * @return The count of blkDataNodes.
     */
    public int getBlkDataNodesCount() {
      return blkDataNodes_.size();
    }

    /**
     * <code>repeated string blkDataNodes = 11;</code>
     *
     * @param index The index of the element to return.
     * @return The blkDataNodes at the given index.
     */
    public String getBlkDataNodes(int index) {
      return blkDataNodes_.get(index);
    }

    /**
     * <code>repeated string blkDataNodes = 11;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the blkDataNodes at the given index.
     */
    public com.google.protobuf.ByteString
    getBlkDataNodesBytes(int index) {
      return blkDataNodes_.getByteString(index);
    }

    /**
     * <code>repeated string blkDataNodes = 11;</code>
     *
     * @param index The index to set the value at.
     * @param value The blkDataNodes to set.
     * @return This builder for chaining.
     */
    public Builder setBlkDataNodes(
        int index, String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureBlkDataNodesIsMutable();
      blkDataNodes_.set(index, value);
      onChanged();
      return this;
    }

    /**
     * <code>repeated string blkDataNodes = 11;</code>
     *
     * @param value The blkDataNodes to add.
     * @return This builder for chaining.
     */
    public Builder addBlkDataNodes(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureBlkDataNodesIsMutable();
      blkDataNodes_.add(value);
      onChanged();
      return this;
    }

    /**
     * <code>repeated string blkDataNodes = 11;</code>
     *
     * @param values The blkDataNodes to add.
     * @return This builder for chaining.
     */
    public Builder addAllBlkDataNodes(
        Iterable<String> values) {
      ensureBlkDataNodesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, blkDataNodes_);
      onChanged();
      return this;
    }

    /**
     * <code>repeated string blkDataNodes = 11;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearBlkDataNodes() {
      blkDataNodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }

    /**
     * <code>repeated string blkDataNodes = 11;</code>
     *
     * @param value The bytes of the blkDataNodes to add.
     * @return This builder for chaining.
     */
    public Builder addBlkDataNodesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      ensureBlkDataNodesIsMutable();
      blkDataNodes_.add(value);
      onChanged();
      return this;
    }

    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:ProtoFileInfo)
  }

}

